apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-alloy
  namespace: argocd
spec:
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - cilium-sandbox-values.yaml
      - alloy-configmaps-values.yaml
    path: grafana-stack/alloy
    repoURL: https://github.com/careroms-personal/sandbox-infra-software.git
    targetRevision: main
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
