apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  destination:
    namespace: prometheus
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - cilium-sandbox-values.yaml
    path: kube-prometheus-stack
    repoURL: https://github.com/careroms-personal/sandbox-infra-software.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
