kubeProxyReplacement: true
k8sServiceHost: d2d-cilium-sandbox-control-plane
k8sServicePort: 6443

ipam:
  mode: kubernetes

operator:
  replicas: 1

hostPort:
  enabled: true

nodePort:
  enabled: true

externalIPs:
  enabled: true

image:
  pullPolicy: IfNotPresent

hubble:
  enabled: true
  relay:
    enabled: true
    tolerations:
      - key: node-role
        operator: Exists
        effect: NoSchedule
  ui:
    enabled: true
    tolerations:
      - key: node-role
        operator: Exists
        effect: NoSchedule
